# Generated by Django 5.2.6 on 2025-09-24 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('DepName', models.CharField(default='00000', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Name',
            field=models.CharField(default='00000', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Name2',
            field=models.CharField(default='00000', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Password',
            field=models.CharField(default='00000', max_length=128),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='global_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Staff'), (3, 'Student'), (4, 'Publisher')], default=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Email',
            field=models.EmailField(default='00000', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='DeptoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.department')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('Department', 'User'), name='unique_department_user')],
            },
        ),
    ]
