# Generated by Django 5.2.6 on 2025-09-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(max_length=100, null=True, verbose_name='firstname:'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(max_length=100, null=True, verbose_name='lastname:'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='temp', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
