# Generated by Django 5.2.6 on 2025-09-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_customuser_firstname_customuser_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
