# Generated by Django 5.2.6 on 2025-09-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Password',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Email',
            field=models.EmailField(default='00000,unique=True', max_length=254, verbose_name='email address'),
        ),
    ]
