# Generated by Django 5.2.6 on 2025-09-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
