# Generated by Django 5.2.6 on 2025-09-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0006_remove_customuser_id_customuser_global_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='global_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
