# Generated by Django 5.2.6 on 2025-09-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0007_remove_customuser_global_id_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='global_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
