# Generated by Django 5.2.6 on 2025-09-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0008_remove_customuser_id_customuser_global_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(default='tmp', max_length=100, verbose_name='firstname:'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default='tmp', max_length=100, verbose_name='lastname:'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='tmp', max_length=150),
        ),
    ]
