# Generated by Django 5.2.6 on 2025-09-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0009_alter_customuser_firstname_alter_customuser_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='global_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
