# Generated by Django 5.2.6 on 2025-09-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0004_remove_customuser_password_alter_customuser_email'),
        ('authuser', '0010_remove_customuser_global_id_customuser_id'),
    ]

    operations = [
    ]
