# Generated by Django 5.2.6 on 2025-09-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0011_merge_20250929_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Name2',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Phone',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Staff'), (3, 'Student')], default=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='00000', max_length=100, unique=True),
        ),
    ]
