# Generated by Django 5.2.6 on 2025-09-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0012_rename_email_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='00000', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
