# Generated by Django 5.2.6 on 2025-10-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0013_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('TagID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('TagName', models.CharField(default='00000', max_length=100)),
            ],
        ),
    ]
