# Generated by Django 5.2.6 on 2025-10-02 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0013_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='staff',
            field=models.ManyToManyField(related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DeptoUser',
        ),
    ]
