# Generated by Django 5.2.6 on 2025-10-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0003_rename_tags_publication_event_tag_and_more'),
        ('authuser', '0014_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
