# Generated by Django 5.2.6 on 2025-10-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0015_rename_fullname_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
