# Generated by Django 5.2.6 on 2025-10-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0015_rename_tags_tag'),
        ('authuser', '0016_rename_first_name_customuser_fullname_and_more'),
    ]

    operations = [
    ]
