# Generated by Django 5.2.6 on 2025-10-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0017_merge_20251008_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
