# Generated by Django 5.2.6 on 2025-10-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0018_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'users'},
        ),
    ]
