# Generated by Django 5.2.6 on 2025-10-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0019_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
