# Generated by Django 5.2.6 on 2025-11-04 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0023_alter_customuser_options_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='DepName',
            field=models.CharField(default='00000', max_length=100, verbose_name='Department name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='departments', to=settings.AUTH_USER_MODEL, verbose_name='Publisher'),
        ),
    ]
