# Generated by Django 5.2.6 on 2025-10-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authuser', '0014_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication_Event',
            fields=[
                ('Event_PublicationID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Author', models.CharField(default='00000', max_length=200)),
                ('EventTitle', models.CharField(default='00000', max_length=200)),
                ('EventDesc', models.TextField(default='00000')),
                ('EventDate', models.DateField()),
                ('PublicationDate', models.DateField(auto_now_add=True)),
                ('Email', models.EmailField(default='00000', max_length=200)),
                ('Organization', models.CharField(default='00000', max_length=200)),
                ('EventLocation', models.CharField(default='00000', max_length=200)),
                ('Department', models.ManyToManyField(related_name='Event_Publications', to='authuser.department')),
                ('Tags', models.ManyToManyField(related_name='Event_Tags', to='authuser.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Publication_News',
            fields=[
                ('News_PublicationID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Author', models.CharField(default='00000', max_length=200)),
                ('NewsTitle', models.CharField(default='00000', max_length=200)),
                ('NewsDesc', models.TextField(default='00000')),
                ('PublicationDate', models.DateField(auto_now_add=True)),
                ('Email', models.EmailField(default='00000', max_length=200)),
                ('Organization', models.CharField(default='00000', max_length=200)),
                ('Department', models.ManyToManyField(related_name='News_Publications', to='authuser.department')),
                ('Tags', models.ManyToManyField(related_name='News_Tags', to='authuser.tags')),
            ],
        ),
    ]
