# Generated by Django 5.2.6 on 2025-10-06 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication_event',
            name='CustomUser',
            field=models.ManyToManyField(related_name='Event_Attendees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication_event',
            name='EventTime',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='publication_event',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication_news',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
