# Generated by Django 5.2.6 on 2025-10-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0002_publication_event_customuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication_event',
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='publication_news',
            old_name='Tags',
            new_name='Tag',
        ),
    ]
