# Generated by Django 5.2.6 on 2025-10-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0003_rename_tags_publication_event_tag_and_more'),
        ('authuser', '0015_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication_event',
            name='Tag',
            field=models.ManyToManyField(related_name='Event_Tag', to='authuser.tag'),
        ),
    ]
