# Generated by Django 5.2.6 on 2025-10-08 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0004_alter_publication_event_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication_event',
            old_name='EventTime',
            new_name='EventEndTime',
        ),
        migrations.RemoveField(
            model_name='publication_event',
            name='EventDate',
        ),
        migrations.AddField(
            model_name='publication_event',
            name='EventEndDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publication_event',
            name='EventStartDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publication_event',
            name='EventStartTime',
            field=models.TimeField(default='00:00'),
        ),
    ]
