# Generated by Django 5.2.6 on 2025-10-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0004_alter_publication_event_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='event_files/')),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Publication.publication_event')),
            ],
        ),
    ]
