# Generated by Django 5.2.6 on 2025-10-08 08:04

import Publication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0005_eventfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfile',
            name='File',
            field=models.FileField(upload_to=Publication.models.event_upload_dir),
        ),
    ]
