# Generated by Django 5.2.6 on 2025-10-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0005_rename_eventtime_publication_event_eventendtime_and_more'),
        ('Publication', '0006_alter_eventfile_file'),
    ]

    operations = [
    ]
