# Generated by Django 5.2.6 on 2025-10-08 12:30

import Publication.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0007_merge_20251008_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to=Publication.models.news_upload_dir)),
                ('News', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Publication.publication_news')),
            ],
        ),
    ]
