# Generated by Django 5.2.6 on 2025-10-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0008_newsfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication_event',
            options={'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='publication_news',
            options={'verbose_name_plural': 'news'},
        ),
    ]
