# Generated by Django 5.2.6 on 2025-10-22 13:31

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0009_alter_publication_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication_event',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Recurring_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('interval', models.IntegerField()),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('until', models.DateField(blank=True, null=True)),
                ('bymonth', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]), size=None)),
                ('bymonthday', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]), size=None)),
                ('byyearday', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)]), size=None)),
                ('byweekno', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(52), django.core.validators.MinValueValidator(1)]), size=None)),
                ('byweekday', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]), size=None)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_events', to='Publication.publication_event')),
            ],
        ),
    ]
