# Generated by Django 5.2.6 on 2025-10-22 13:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0010_publication_event_is_recurring_recurring_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_event',
            name='byweekday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True), size=None),
        ),
        migrations.AlterField(
            model_name='recurring_event',
            name='freq',
            field=models.IntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Yearly')]),
        ),
    ]
