# Generated by Django 5.2.6 on 2025-10-22 13:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0011_alter_recurring_event_byweekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_event',
            name='byweekday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True), blank=True, null=True, size=None),
        ),
    ]
