# Generated by Django 5.2.6 on 2025-10-22 13:39

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0012_alter_recurring_event_byweekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_event',
            name='bymonth',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='recurring_event',
            name='bymonthday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='recurring_event',
            name='byweekno',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(52), django.core.validators.MinValueValidator(1)]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='recurring_event',
            name='byyearday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)]), blank=True, null=True, size=None),
        ),
    ]
