# Generated by Django 5.2.6 on 2025-10-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0013_alter_recurring_event_bymonth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_event',
            name='interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
