# Generated by Django 5.2.6 on 2025-10-23 11:58

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0014_alter_recurring_event_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.IntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Yearly')])),
                ('interval', models.IntegerField()),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('until', models.DateField(blank=True, null=True)),
                ('bymonth', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True), blank=True, null=True, size=None)),
                ('bymonthday', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]), blank=True, null=True, size=None)),
                ('byyearday', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)]), blank=True, null=True, size=None)),
                ('byweekno', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(52), django.core.validators.MinValueValidator(1)]), blank=True, null=True, size=None)),
                ('byweekday', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True), blank=True, null=True, size=None)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_events', to='Publication.publication_event')),
            ],
        ),
        migrations.DeleteModel(
            name='Recurring_Event',
        ),
    ]
