# Generated by Django 5.2.6 on 2025-10-23 17:39

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0015_recurringevent_delete_recurring_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringevent',
            name='weekday_byday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (-2, 'Next to last'), (-1, 'Last')], null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='bymonthday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(-30)]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='byyearday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(-364)]), blank=True, null=True, size=None),
        ),
    ]
