# Generated by Django 5.2.6 on 2025-10-26 05:25

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0016_recurringevent_weekday_byday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringevent',
            name='rrule',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='byweekno',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(52), django.core.validators.MinValueValidator(-51)]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='weekday_byday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(0, '-'), (1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (-2, 'Next to last'), (-1, 'Last')], null=True), blank=True, null=True, size=None),
        ),
    ]
