# Generated by Django 5.2.6 on 2025-10-26 05:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0017_recurringevent_rrule_alter_recurringevent_byweekno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringevent',
            name='byweekday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True), blank=True, null=True, size=None),
        ),
    ]
