# Generated by Django 5.2.6 on 2025-10-26 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0018_alter_recurringevent_byweekday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringevent',
            old_name='Event',
            new_name='event',
        ),
    ]
