# Generated by Django 5.2.6 on 2025-10-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0019_rename_event_recurringevent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringevent',
            name='dtstart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringevent',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
