# Generated by Django 5.2.6 on 2025-10-26 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0020_recurringevent_dtstart_recurringevent_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication_event',
            name='EventEndTime',
        ),
        migrations.RemoveField(
            model_name='publication_event',
            name='EventStartTime',
        ),
        migrations.AlterField(
            model_name='publication_event',
            name='EventEndDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='publication_event',
            name='EventStartDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
