# Generated by Django 5.2.6 on 2025-10-26 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0021_remove_publication_event_eventendtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication_event',
            name='EventEndTime',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='publication_event',
            name='EventStartTime',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='publication_event',
            name='EventEndDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='publication_event',
            name='EventStartDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
