# Generated by Django 5.2.6 on 2025-11-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0022_publication_event_eventendtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication_event',
            name='Username',
            field=models.CharField(default='00000', max_length=200),
        ),
    ]
