name: django-postgres-project
networks:
  maildev_network:
    external: true
services:
  app:
    build: .
    image: app-image
    depends_on:
      postgres:
        condition: service_healthy
    container_name: deploy-softeng-2025-1-web
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: "sh ./gitlab"
  postgres:
    image: postgres
    volumes:
      - /tmp/group1/postgres-data:/var/lib/lib/postgresql/data
    container_name: deploy-softeng-2025-1-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 10s
volumes:
  db: null
