# Generated by Django 5.2.6 on 2025-10-16 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0009_alter_publication_event_options_and_more'),
        ('attendance', '0002_eventattendance_allergies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventattendance',
            options={},
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='allergies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='dietary_preferences',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='Publication.publication_event'),
        ),
    ]
